language: scala
dist: trusty
addons:
  sonarcloud:
    organization: rafaelspinto-github
    token:
      secure: OIqJhaCp+dam8gh0fg6yzSvhvIOVQ9OCNCkAjf8MK8At4r0E2+vkug4Fn+LTVd/WWdHCbjRzfFbIYiBrtjlmWxdwBfWdva6SPgPpcIhk1mfmf9r6JVKKeSBh+xAslQL7bya3gh+ao/90JnYHXJHnBSbCHu7fhfulGj2yH6l5e511RPpc2JVfsd5rmEX9UN2rJVBnV/SrqOKhoWwsCDlxtnjT2kJzZtxSDqVyKIhjZbMJDM6KiHV29t1X4xGFrQbGygbqc8ZYiUILnRq9bichO+oFqgEgbaZVTeN74eKMjvKm1NpcAGWUQs6G+WX1GoGdVeUdQmf8KTsUDmzpG4dbA+aTUJAxJ7tUC8yNPWaCPqGC5Xm12uAXa87TLlB5MVmre0PpgVCFLZ1ZVeWBP1BToiPqjVEHZSpJjBdFC9ckzAU2pSV6pk/ccloQoJVahbcTDli7CYPXLpFhO6jnSBV6TlTm19FM2BZUiI6YDUpAJtGj1/AkgI/D9Xs08N8YFzZOeYu5zXg/vBNlXpBo/pkdMtMVy693sQabuxCNPJ4dUXw9Qp4pn0MU/Vhfjy/+MgMu/zfs4A3G2ooiT9ltt8Cj8tclVz+xFE+PWJ/dDMLexLkVIA4OYvVLb7/glLS91LHLJpxuQPhylEO4sBzMJBV9vIEGNgJl+J3OKtKiq3xv48c=
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
- mvn test